version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:openjdk-11
    steps:
      - checkout
      - run:
          name: test
          command: mvn clean test

workflows:
  maven_test:
    jobs:
      - test
