version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: test
          command: mvn test
      - run:
          name: cobertura
          command: mvn cobertura:cobertura
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  maven_test:
    jobs:
      - test
